# Generated by Django 4.1.2 on 2022-10-08 03:21

from django.db import migrations, models
import modulos.producto.validators


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[modulos.producto.validators.validar_costo_producto], verbose_name='Costo del Producto $us'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[modulos.producto.validators.validar_stock_minimo], verbose_name='Stock del Producto'),
        ),
    ]
